CREATE TABLE IF NOT EXISTS users (
  user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login varchar NOT NULL,
  name varchar,
  email varchar NOT NULL,
  birthday date NOT NULL,
  CONSTRAINT uq_email UNIQUE(email),
  CONSTRAINT uq_login UNIQUE(login)
);

CREATE TABLE IF NOT EXISTS friends (
  user1_id integer REFERENCES users(user_id),
  user2_id integer REFERENCES users(user_id),
  PRIMARY KEY (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS mpa (
    mpa_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
  film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200) NOT NULL,
  duration integer NOT NULL,
  release_date date NOT NULL,
  mpa_id INTEGER REFERENCES mpa(mpa_id)
  );

CREATE TABLE IF NOT EXISTS likes (
  film_id integer REFERENCES films(film_id),
  user_id integer REFERENCES users(user_id),
  PRIMARY KEY (user_id, film_id)
  );

CREATE TABLE IF NOT EXISTS genres (
 genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 genre_name varchar NOT NULL UNIQUE
 );

CREATE TABLE IF NOT EXISTS film_genres (
 film_id integer REFERENCES films(film_id),
 genre_id integer REFERENCES genres(genre_id),
 PRIMARY KEY (film_id, genre_id)
 );
